import numpy as np
from matplotlib import pyplot as plt
plt.style.use('dark_background')
pcas_4 = np.load('pcas_4.npy')
pcas_10 = np.load('pcas_10.npy')
fig = plt.figure()
X = np.arange(8)
ax = fig.add_subplot(111)
ax.set_xlim(.5, 7.7)
ax.bar(X + 0.00, pcas_10, color = 'b', width = 0.25)
ax.bar(X + 0.25, pcas_4, color = 'g', width = 0.25)
plt.xlabel('Number qubits = $2^n$ features')
plt.title('Explained Variance per number qubits on MNIST dataset')
plt.ylabel('Explained Variance %')
plt.legend(labels=['10 digits', '4 digits'])
plt.show()